### ISSUE TITLE
OR Mavenization: Application icon/symbol is different

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-online-review#127]
Description:

Application icon/symbol is different in Mavenized OR and old OR.

![image](https://user-images.githubusercontent.com/55895538/162174566-6dce51a6-f4ea-4e30-ae87-f795167b7e6c.png)
![image](https://user-images.githubusercontent.com/55895538/162174625-2bc4937f-1963-4887-9b09-3571aab38348.png)

**Comment by xxcxy** [comment]
don't find such icon in source code, could you capture these two icon url?

**Comment by sandhiyakavi** [comment]
@xxcxy  Mavenized OR : https://softwarev1.topcoder-dev.com/i/appSm.gif

For old OR: https://software.topcoder-dev.com/i/appSm.gif

**Comment by sandhiyakavi** [comment]
@Gunasekar-K  Still I am able to see the same different icon/symbol for Application

sample:
Mavenize OR: https://softwarev1.topcoder-dev.com/review/actions/ListProjects?scope=my
Old OR: https://software.topcoder-dev.com/review/actions/ListProjects?scope=my

![image](https://user-images.githubusercontent.com/55895538/162719784-ba83320c-8230-4a34-ad7c-23b9178b1f2d.png)

![image](https://user-images.githubusercontent.com/55895538/162719839-76bd06b7-4df0-42e4-8520-c0d206c6d6b2.png)

**Comment by Gunasekar-K** [comment]
@sandhiyakavi Kindly try in incognito
<img width="980" alt="image" src="https://user-images.githubusercontent.com/28942591/162732674-6c6bc682-777e-46a0-94d9-8fae0b7fd054.png">

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Application symbol/icon is displaying correctly now.

![image](https://user-images.githubusercontent.com/55895538/162877618-46f2c361-c2e4-4fa1-a5ec-29bdb3896e9a.png)
