### ISSUE TITLE
OR Mavenization: Resource's userhandle links are directing to production Environment

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-online-review#128]
Description:

Resource's userhandle links are directing to production Environment instead of Dev Environment (as in old OR).

![image](https://user-images.githubusercontent.com/55895538/162176426-b0cfa2f0-98ed-483f-b34b-cbbaaf557655.png)

![image](https://user-images.githubusercontent.com/55895538/162176355-7a81b042-5994-473f-be23-55315ffab77a.png)

**Comment by standlove** [comment]
It's configure issue ...  @Gunasekar-K   should we look into this or leave it?

**Comment by standlove** [comment]
SERVER_NAME=www.topcoder-dev.com - please update the SERVER_NAME in the token properties file.  @Gunasekar-K

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Resource's userhandle links are directing to the Dev Environment now.

![image](https://user-images.githubusercontent.com/55895538/163095762-9a7c4bb3-40b2-469d-8023-edc0c9f8f034.png)
