### ISSUE TITLE
OR Mavenization: Login/Logout is not working in OR

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-online-review#129]
Description:

The Login and Logout processes are not working in the new OR. Also the Login screen is different and not redirecting to the auth login screen.

1. Mavenized OR Login screen:

![image](https://user-images.githubusercontent.com/55895538/162359788-c8489943-fa21-442d-a9dc-70db8046421e.png)

2. If tried to login from the login screen, getting error message.

https://user-images.githubusercontent.com/55895538/162359849-278f5fd5-3f9b-4684-b423-33c971fe4c49.mp4

<img width="960" alt="OR_login_error" src="https://user-images.githubusercontent.com/55895538/162359919-6666c242-7412-44df-84f1-5fec7eee31b7.png">

3. Logout in Mavenized OR redirects to login screen but not logged out.

![image](https://user-images.githubusercontent.com/55895538/162359998-2738332f-57f0-43e5-ac33-d36dcfc13c8d.png)

**Comment by standlove** [comment]
@Gunasekar-K   Can you post that login/logout details to here again?

**Comment by sandhiyakavi** [comment]
verified in Dev Env. Login and Logout is working as expected.


https://user-images.githubusercontent.com/55895538/162714284-374b270e-d11f-4c59-aba6-72d212b9843e.mp4
