### ISSUE TITLE
Not able to save the scorecard for later use

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-online-review#132]
Description:

The Reviewer is not able to save the half-filled/filled scorecard with the "Save for later" button. Clicking the button gives error message.

https://user-images.githubusercontent.com/55895538/162402241-2944d4ac-b3ac-4533-9d7a-c67dc64e7aab.mp4

**Comment by standlove** [comment]
should be working now.  @sandhiyakavi

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Able to save the scorecard for later use now.


https://user-images.githubusercontent.com/55895538/162672810-0d48a9e0-9f80-4018-b47e-1e3e2d1248dd.mp4
