### ISSUE TITLE
OR Mavenization: Reviewer is not able to submit the Review scorecard

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-online-review#133]
Description:

Reviewer is not able to submit the Review scorecard

https://user-images.githubusercontent.com/55895538/162402835-a0bb555a-8f97-4614-a079-4ba280154d2b.mp4

**Comment by sandhiyakavi** [comment]
Similar issue is happening for iterative Reviewer (for F2F challenges)

**Comment by standlove** [comment]
Should be working now.  @sandhiyakavi

**Comment by sandhiyakavi** [comment]
verified in Dev Env. Able to submit the Review scorecard now.



https://user-images.githubusercontent.com/55895538/162726398-2c19b31c-d7d7-40d9-862c-b9f369e38dcd.mp4


https://user-images.githubusercontent.com/55895538/162726563-a9aa6acc-0ccd-4e22-843e-3bc9b2821953.mp4
