### ISSUE TITLE
Register button is not enabled for challenges in Community app if Registration phase opened from Mavenized OR

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-online-review#134]
Description:

Register button is not enabled for challenges in Community app if Registration phase opened from Mavenized OR.

Mavenized OR sample challenge: https://www.topcoder-dev.com/challenges/e5e0bd72-bc02-41cb-8dff-a79e2d34aaa7
OR link: https://softwarev1.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30061242

![image](https://user-images.githubusercontent.com/55895538/162405897-f7e82203-2941-4e9f-9d76-e84fc1904f59.png)

![image](https://user-images.githubusercontent.com/55895538/162405991-74934470-c37c-4d34-ac4a-56403e660237.png)

Old OR sample challenge: https://www.topcoder-dev.com/challenges/3fc2366a-6e7a-4646-ad24-7c31c5563e16
OR link: https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30061245

**Comment by SathyaJayabal** [comment]
Adding to the above, even though the phase shows as open in OR, the registration phase is still closed is both v4 and v5 for the above example challenge. So it looks like the opening of the registration phase from the new OR is not going through properly to even v4.

**Comment by SathyaJayabal** [comment]
Now these phases are open, Will test this again on monday.
cc @sandhiyakavi

**Comment by standlove** [comment]
I think there is another job to sync the data.

**Comment by standlove** [comment]
I think there is another job to sync the data.

**Comment by sandhiyakavi** [comment]
This issue is resolved. Register button is getting enabled for challenges in Community app now.

![image](https://user-images.githubusercontent.com/55895538/162665625-b2302c2d-0172-4e0f-8bd8-29a42add36ad.png)

sample challenge: https://www.topcoder-dev.com/challenges/c749c9ee-e0c5-4416-9420-daa397feb52b
