### ISSUE TITLE
Beta OR: Reviewer not able to Submit the Review scorecard

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-online-review#149]
Description:
Reviewer not able to Submit the Review scorecard in Beta OR. Getting error message.

https://user-images.githubusercontent.com/55895538/165449189-e1e07b73-3605-4732-850e-41b2676c0bd1.mp4

**Comment by Gunasekar-K** [comment]
[Uploading log-events-viewer-result_1.csv…]()

**Comment by Gunasekar-K** [comment]
[log-events-viewer-result_1.csv](https://github.com/topcoder-platform/tc-online-review/files/8569508/log-events-viewer-result_1.csv)
[log-events-viewer-result_1.csv](https://github.com/topcoder-platform/tc-online-review/files/8569510/log-events-viewer-result_1.csv)

**Comment by sandhiyakavi** [comment]
Similar issue happens for Iterative Review as well.


https://user-images.githubusercontent.com/55895538/165458944-245795ee-699d-4425-b43e-df499ffd6b0d.mp4

**Comment by Gunasekar-K** [comment]
nfs_share mount has fixed on task definition

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Reviewer/Iterative Reviewer able to submit the scorecard.

sample: https://challenges.topcoder.com/projects/32730/challenges/a8ed9bc7-bef9-4806-b7f0-22958a3c44df/view
https://challenges.topcoder.com/projects/32730/challenges/6da97f32-5a8d-48dc-9aa6-524b75819ada/view
