### ISSUE TITLE
Event Bus Integration -Topic name needs to be configurable

### ISSUE THREAD

**Issue by BadalZ** [topcoder-platform/tc-online-review#27]
Topic name is hard coded as in EventMessage.java Keep it configurable in property file.

Also we need to use separate topic for create, update & delete action like below

**For Submission actions:**
notifications.or.submission.create
notifications.or.submission.update
notifications.or.submission.delete

**For review actions:**
notifications.or.review.create
notifications.or.review.update
notifications.or.review.delete

CC: @cwdcwd & @coderReview

**Comment by coderReview** [comment]
@BadalZ let's work on this after Maven change. What do you think?

**Comment by cwdcwd** [comment]
are these topics formatted right according to the standard?

**Comment by BadalZ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use different topic name in Online Review](https://trello.com/c/eN1nELAf/33-use-different-topic-name-in-online-review)

**Comment by coderReview** [comment]
@BadalZ topic is not configurable

current value `or.notifications.create`
